### ISSUE TITLE
Intermittent timeouts

### ISSUE THREAD

**Issue by radiallogic** [aws/aws-iot-device-sdk-python#277]
I'm receiving intermittent timeouts while publishing or subscribing on all IoT devices on different networks, including an EC2 instance. I've been through this with AWS support who suggested coming here. His comments are below. 

You are observing random timeouts on 13 probes (IoT things) across globe. The probes are running AWSIoTPythonSDKv1. Based on the device side logs, the following SDK code is being executed[1]. 

grep -rnw . -e 'Performing sync publish'
./core/protocol/mqtt_core.py:262:        self._logger.info("Performing sync publish...")
Binary file ./core/protocol/__pycache__/mqtt_core.cpython-37.pyc matches

grep -rnw . -e 'Publish timed out'
./core/protocol/mqtt_core.py:272:        self._logger.error("Publish timed out")

In order to further troubleshoot the issue I requested your client side code to try and replicate the issue. I was able to successfully replicate the issue in my test environment and further trace back the error inside SDK to isolate where the code execution halts waiting for PUBACK message from AWS IoT Core till MQTTOperationTimeout value expires[2]. Following is a quick run through:

Inside loop function * [3] > Calls loop_read [4] > loop_read function [5] > Calls _packet_read [6] > packet_read function [7] > Calls _packet_handle [8] > _packet_handle function [9] > Calls _handle_pubackcomp [10] > _handle_pubackcomp function [11] > Calls on_publish [12] > on_publish function [13] > Calls _add_to_queue [14] > The code waits here till the MQTTOperationtimesout [15].

	* - Call loop() frequently to maintain network traffic flow with the broker.

Since this behavior was observed because PUBACK is not received, I confirmed from the IoT service team PUBACK has been sent from IoT core successfully to the publish messages. Hence, I tested the client code in my test environment by lowering the MQTTOperationtimeout value which yielded better results. 

Taking into consideration the above mentioned troubleshooting, I recommended you to reach out to Github issue[16] since the SDK team actively monitors and maintains github issue page.

I'm subscribing to the queue with 

    def setupQueueClient(self): 
        self.QueueClient = self.ShadowClient.getMQTTConnection()
        self.QueueClient.configureOfflinePublishQueueing(-1, DROP_OLDEST)
        self.QueueClient.connect()

        self.QueueClient.configureAutoReconnectBackoffTime(1, 128, 20)
        self.QueueClient.configureConnectDisconnectTimeout(15) 
        self.QueueClient.configureMQTTOperationTimeout(5) 
        self.QueueClient.connect()

and publishing with 

    def publish(self, payload, topic = "data"):
        if self.QueueClient == None: 
            self.setupQueueClient()
            
        payload["thing"] = self.config.data['thingName'] 
        message = json.dumps( payload )

        log.info("publishing payload") 
        log.info(message)

        try:
            self.QueueClient.publish(topic, message, QoS=1) 
        except publishTimeoutException as e:
            log.info(str(e))
            #self.publish(payload, topic)

and subscribing with 

    def updateSubscribe(self):
        log.debug('*** Subscribe to update channel') 
        if self.QueueClient == None: 
            self.setupQueueClient()
            
        self.QueueClient.subscribe("update", 1, self.processMessage)  # QoS=1

**Comment by DavidOgunsAWS** [comment]
I'm looking at [our use of condition here](https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/mqtt_core.py#L71) and suspecting that because it's [not actually thread-safe](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Condition), [Here](https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/internal/workers.py#L62) and [here](https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/internal/workers.py#L142) aren't playing nice.  [This code](https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/internal/workers.py#L112) makes it clear _dispatch() is running in another thread.

I'll try to repro. Can you give me an idea of what rate of QoS1 publishes and how long it takes for timeouts to occur?

Thanks

**Comment by radiallogic** [comment]
During testing we were sending messages manually, it took between 1-4
messages for the client to stop responding.

Thanks

**Comment by DavidOgunsAWS** [comment]
I was able to get details from the support engineer and the adjustment needed is to push any calls to publish() outside of any MQTT operation callback handler. The broader rule is: _do not perform MQTT operations within an MQTT operation callback_ for this SDK.

To address this quickly you can spawn a thread to do the publish like so: https://github.com/aws/aws-iot-device-sdk-python/blob/master/samples/jobs/jobsSample.py#L92 -- sendJobsStartNext contains the call to publish(). This will let the handler return and still do the work.

This code calls connect twice this should be fixed too:
```
def setupQueueClient(self): 
    self.QueueClient = self.ShadowClient.getMQTTConnection()
    self.QueueClient.configureOfflinePublishQueueing(-1, DROP_OLDEST)
    self.QueueClient.connect()

    self.QueueClient.configureAutoReconnectBackoffTime(1, 128, 20)
    self.QueueClient.configureConnectDisconnectTimeout(15) 
    self.QueueClient.configureMQTTOperationTimeout(5) 
    self.QueueClient.connect()
```

Also, the prior suspicion about the Condition variable was incorrect. threading.Condition is thread safe as opposed to asyncio.Condition

**Comment by radiallogic** [comment]
Hi David,

Thanks for your response, I'll definitely update the double connect issue.

I've tried publishing in a separate thread using

threading.Thread(target = self.QueueClient.publish, kwargs = {'topic':
topic, 'payload': message, 'QoS': 1}).start()

and separately Omkar's suggested

self.QueueClient.publishAsync(topic, message, QoS=1)

I don't see timeouts anymore, but I also don't see the published message on
the aws test interface. I'll copy and paste my local device logs.

Jan 21 08:59:08 ip-172-31-24-139 python3[17427]: INFO:Segundo
main.py:message recieved
Jan 21 08:59:08 ip-172-31-24-139 python3[17427]: INFO:Segundo
main.py:{'type': 'ping', 'target': 'all'}
Jan 21 08:59:08 ip-172-31-24-139 python3[17427]: INFO:Segundo
main.py:publishing payload
Jan 21 08:59:08 ip-172-31-24-139 python3[17427]: INFO:Segundo
main.py:{"type": "v0.1.1_ping", "thing":
"76bc188b-69d7-4a6e-8995-112f1b568502"}
Jan 21 08:59:08 ip-172-31-24-139 python3[17427]: 2021-01-21 08:59:08,897 -
AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async publish...
Jan 21 08:59:08 ip-172-31-24-139 python3[17427]:
INFO:AWSIoTPythonSDK.core.protocol.mqtt_core:Performing async publish...
Jan 21 08:59:08 ip-172-31-24-139 python3[17427]: 2021-01-21 08:59:08,898 -
AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom
event callback...
Jan 21 08:59:08 ip-172-31-24-139 python3[17427]:
DEBUG:AWSIoTPythonSDK.core.protocol.internal.clients:Invoking custom event
callback...
Jan 21 08:59:08 ip-172-31-24-139 python3[17427]: 2021-01-21 08:59:08,910 -
AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [puback]
event
Jan 21 08:59:08 ip-172-31-24-139 python3[17427]:
DEBUG:AWSIoTPythonSDK.core.protocol.internal.workers:Produced [puback] event
Jan 21 08:59:08 ip-172-31-24-139 python3[17427]: 2021-01-21 08:59:08,910 -
AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching
[puback] event
Jan 21 08:59:08 ip-172-31-24-139 python3[17427]:
DEBUG:AWSIoTPythonSDK.core.protocol.internal.workers:Dispatching [puback]
event

Thanks, Max B

**Comment by DavidOgunsAWS** [comment]
Can you be more specific about what this means?
> I don't see timeouts anymore, but I also don't see the published message on
the aws test interface.

If the publish is working and you're getting a puback, there's now another problem. I don't have a helpful understanding of the new issue from the log lines you posted. Can you gather specific data about what you're expecting to have happen next, and what you observe to be failing in the SDK?

**Comment by radiallogic** [comment]
Hi David,
I’m not sure this is an SDK issue, I’m still seeing the same connection
issues I was previously. Sorry for not being clearer in my message. I’ve
left this in the hands of AWS support for now.

Thank you for your time on this.

Kind regards, Max Brooks
